### PR TITLE
Why httpd?

### PR DESCRIPTION
**Pull request by LinkBR**
The package "php" install httpd, we dont need it.

### CODE REVIEW

**Comment by danielisaksen** [comment]
Seems pointless to remove, especially considering it might not be a dependency on all mirror setups. Just a thought.

**Comment by LinkBR** [comment]
Okay, but it's just a package less to install :)

**Comment by danielisaksen** [comment]
It is not a package less if the package php or php-common installs it as a dependency either way though. ;)

**Comment by LinkBR** [comment]
Nope, php-common dont install httpd.

**Comment by danielisaksen** [comment]
`php` is a metapackage, check if all the `php-*` (libraries) packages it 
installs are installed and I will push your patch to testing.

**Comment by Feathur** [comment]
I don't think we need the package httpd either... just haven't written a new installer yet so when I do it'll only install what it needs.

**Pull request closed without merging**
